version: "3.8"

services:
  postgres:
    container_name: commodiAI-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - opensearch-net

  localstack:
    container_name: "commodiAI-${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - opensearch-net

  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: commodiAI-opensearch-node
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - "9201:9200" # REST API
      - "9600:9600" # Performance Analyzer
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: commodiAI-opensearch-dashboards
    ports:
      - "5602:5601" # Map host port 5602 to container port 5601
    expose:
      - "5602" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9201"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    networks:
      - opensearch-net

  backend:
    build: .
    container_name: commodiAI-backend
    volumes:
      - $PWD/gen_ai:/app/gen_ai
    ports:
      - "8033:8000"
    expose:
      - "8033"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - OPENSEARCH_URL=opensearch-node:9200
      - S3_ENDPOINT=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - opensearch-net
    depends_on:
      - postgres
      - opensearch-node

  frontend:
    build: $PWD/chart_chat_fe
    container_name: commodiAI-frontend
    volumes:
      - $PWD/chart_chat_fe:/app
      - $PWD/chart_chat_fe/node_modules:/app/node_modules
    ports:
      - "3033:3000"
    expose:
      - "3033"
    networks:
      - opensearch-net

volumes:
  opensearch-data:
  postgres-data:

networks:
  opensearch-net:
