"""Add question table.

Revision ID: 1d12e6bef732
Revises: f06b5c59fd81
Create Date: 2023-11-21 16:17:41.979679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1d12e6bef732'
down_revision: Union[str, None] = 'f06b5c59fd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('history_id', sa.UUID(), nullable=False),
                    sa.Column('question', sa.String(), nullable=False),
                    sa.Column('prompted_question', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.execute(
        """
        CREATE TRIGGER update_question_updated_at
            BEFORE UPDATE
            ON
                question
            FOR EACH ROW
        EXECUTE PROCEDURE update_updated_at();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
