"""Add answer table.

Revision ID: d154bcade214
Revises: 1d12e6bef732
Create Date: 2023-11-21 16:19:37.349124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd154bcade214'
down_revision: Union[str, None] = '1d12e6bef732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('history_id', sa.UUID(), nullable=False),
                    sa.Column('question_id', sa.UUID(), nullable=False),
                    sa.Column('str_answer', sa.String(), nullable=True),
                    sa.Column('json_answer', sa.JSON(), nullable=True),
                    sa.Column('has_analysis', sa.BOOLEAN(), nullable=True),
                    sa.Column('type', sa.Enum('JSON', 'STRING', name='chatanswertype'), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    sa.Enum(name="chatanswertype").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
