"""Add default value to history_id in question table.

Revision ID: f751060a30f8
Revises: d154bcade214
Create Date: 2023-11-24 17:17:24.199753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f751060a30f8'
down_revision: Union[str, None] = 'd154bcade214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'prompted_question',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('question', 'history_id',
                    existing_type=sa.UUID(),
                    server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'history_id',
                    existing_type=sa.UUID())
    # ### end Alembic commands ###
